- name: Add Application user
  ansible.builtin.user:
    name: roboshop

- name: Cleaning the Application Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes




#
#echo -e "\e[31m>>>>>>  Create  a  ${component} Service File <<<<<<<<<<<<<\e[0m" | tee -a ${log}
#cp shipping.service /etc/systemd/system/${component}.service &>> ${log}
#
#echo -e "\e[31m>>>>>>  Create Application User <<<<<<<<<<<<<\e[0m"  | tee -a ${log}
#
#useradd roboshop &>> ${log}
#
#echo -e "\e[31m>>>>>>  Cleaning Application  Content <<<<<<<<<<<<<\e[0m"  | tee -a ${log}
#rm -rf /app &>> ${log}
#
#echo -e "\e[31m>>>>>>  Create Application Directory <<<<<<<<<<<<<\e[0m"  | tee -a ${log}
#
#mkdir /app &>> ${log}
#
#echo -e "\e[31m>>>>>>  Downloading  Application Content <<<<<<<<<<<<<\e[0m"  | tee -a ${log}
#
#curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>> ${log}
#cd /app &>> ${log}
#
#echo -e "\e[31m>>>>>>  Extracting  Application Content  <<<<<<<<<<<<<\e[0m"  | tee -a ${log}
#unzip /tmp/${component}.zip &>> ${log}
