- name: Dispatch Setup
  hosts: all
  become: true
  tasks:
    - name: Installing Go lang
      ansible.builtin.yum:
        name: golang
        state: installed


    - name: Unarchive a file that needs to be downloaded
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/dispatch.zip
        dest: /app
        remote_src: yes

    - name: Installing Go packages
      ansible.builtin.shell: go mod init dispatch; go get; go build
      args:
        chdir: /app

    - name: Starting Dispatch Service
      ansible.builtin.systemd:
        name: dispatch
        state: installed
        enabled: yes
        daemon_reload: yes