

- name: Copy file to repos
  ansible.builtin.copy:
    src: {{components}}.service
    dest: /etc/systemd/system//{{components}}.service

- name: Restart the {{components}} Service
  ansible.builtin.systemd:
    name: {{components}}
    state: restarted
    daemon_reload: yes