- name: Copy file to repos
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Installing Go lang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: App Prerequestites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-preq.yml

- name: Installing Go packages
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
    chdir: /app


- name: Starting Dispatch Service
  ansible.builtin.systemd:
    name: dispatch
    state: restarted
    enabled: yes
    daemon_reload: yes